const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        AlignmentType, HeadingLevel, BorderStyle, WidthType, ShadingType, PageBreak } = require('docx');
const fs = require('fs');

const OUT = 'D:\\Mtech Main project\\smartgrid-audit-base-\\Report\\SUBMISSION\\SmartGrid_PPTX_Slide_Content_and_Images.docx';

const bd = { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' };
const borders = { top: bd, bottom: bd, left: bd, right: bd };
const pad = { top: 80, bottom: 80, left: 140, right: 140 };

function sp(n = 1) {
  return Array.from({ length: n }, () => new Paragraph({ children: [new TextRun('')] }));
}

function slideHeader(num, title, tag) {
  return new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [700, 8660],
    rows: [new TableRow({ children: [
      new TableCell({
        borders,
        shading: { fill: '1F3864', type: ShadingType.CLEAR },
        margins: { top: 100, bottom: 100, left: 120, right: 120 },
        verticalAlign: 'center',
        children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: String(num), bold: true, size: 32, color: 'FFFFFF' })] })]
      }),
      new TableCell({
        borders,
        shading: { fill: '2E5A9C', type: ShadingType.CLEAR },
        margins: { top: 100, bottom: 100, left: 200, right: 120 },
        children: [
          new Paragraph({ children: [new TextRun({ text: title, bold: true, size: 26, color: 'FFFFFF' })] }),
          tag ? new Paragraph({ children: [new TextRun({ text: tag, size: 18, color: 'BDD7EE', italics: true })] }) : new Paragraph({ children: [new TextRun('')] }),
        ]
      }),
    ]})]
  });
}

function contentBox(lines) {
  const rows = lines.map(line => {
    const isSub = line.startsWith('  ');
    const text = line.trim();
    const isEmpty = text === '';
    return new TableRow({ children: [new TableCell({
      borders: {
        top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE },
        left: { style: BorderStyle.SINGLE, size: 6, color: '2E5A9C' },
        right: { style: BorderStyle.NONE },
      },
      margins: { top: isEmpty ? 20 : 60, bottom: isEmpty ? 20 : 60, left: isSub ? 440 : 140, right: 100 },
      shading: { fill: 'F8FBFF', type: ShadingType.CLEAR },
      children: [new Paragraph({
        children: isEmpty ? [new TextRun('')] : [new TextRun({ text, size: 20, color: isSub ? '444444' : '111111' })]
      })]
    })] });
  });
  return new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [9360], rows });
}

function imageBox(desc) {
  return new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [400, 8960],
    rows: [new TableRow({ children: [
      new TableCell({
        borders,
        shading: { fill: '4B0082', type: ShadingType.CLEAR },
        margins: { top: 100, bottom: 100, left: 80, right: 80 },
        verticalAlign: 'center',
        children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'IMG', bold: true, size: 16, color: 'FFFFFF' })] })]
      }),
      new TableCell({
        borders,
        shading: { fill: 'F5F0FF', type: ShadingType.CLEAR },
        margins: pad,
        children: [new Paragraph({ children: [new TextRun({ text: desc, size: 20, italics: true, color: '4B0082' })] })]
      }),
    ]})]
  });
}

function pb() { return new Paragraph({ children: [new PageBreak()] }); }

// ─── All 43 slides ────────────────────────────────────────────────────────────
const SLIDES = [

{ num: 1, title: 'Title Slide', tag: 'Cover',
  content: [
    'SmartGrid AI Audit Framework',
    '  Cyber-Physical Monitoring and Audit Intelligence',
    '',
    'Aditya Sanjay Jadhav  (242050010)',
    'Guide: Prof. Shrinivas Khedkar',
    '',
    'Dept. of Computer Engineering & IT  |  VJTI Mumbai',
    'M.Tech Project Presentation  |  2025-26',
  ],
  image: 'FILE: vjtilogo.jpg — Place VJTI logo top-left corner of the slide. Project title in large bold text at centre. Guide name and department in smaller text below the title. Roll number and institute name at bottom-centre. Dark navy blue gradient background.',
},

{ num: 2, title: 'Problem Statement — Why This Project Exists', tag: 'Context',
  content: [
    'Smart grids integrate electrical infrastructure, communication networks, and control systems — a single coordinated attack can compromise all three layers simultaneously.',
    '',
    'Static threshold monitoring flags transient noise as threats and misses slow, persistent attack campaigns.',
    '',
    'Single-layer anomaly detectors cannot distinguish between FDI, DoS, and MITM attack signatures.',
    '',
    'Fixed audit schedules spend budget auditing safe agents and under-audit high-risk ones.',
    '',
    'Operators receive binary alerts with no explanation — they cannot verify or investigate.',
    '',
    'Existing research frameworks are simulation-only — no live SCADA integration has been demonstrated.',
    '',
    'The core question:',
    '  How do you detect multiple attack types, schedule audits intelligently, explain every decision,',
    '  and run it all on live SCADA data?',
  ],
  image: 'FILE: TierArchitecture.png — Place this system overview diagram on the right half of the slide. Shows the four-tier architecture and how physical and cyber layers connect. Resize to fill the right 55% of the slide. Left half of slide has the bullet text. The diagram visually reinforces why a multi-layer approach is needed.',
},

{ num: 3, title: 'Research Objectives', tag: 'NEW — Goals',
  content: [
    'Six objectives framing the entire system design:',
    '',
    '1.  Build a multi-layer anomaly detection system combining statistical deviation analysis,',
    '    temporal LSTM-based detection, and rule-based attack-specific classifiers into one pipeline.',
    '',
    '2.  Pre-train separate LSTM branches on publicly available domain-specific benchmark datasets:',
    '    UCI Electrical Grid Stability for the physical branch, UNSW-NB15 for the cyber branch.',
    '',
    '3.  Design a hybrid audit scheduler combining Q-learning for discrete escalation decisions',
    '    with gradient descent for continuous budget-constrained audit frequency allocation.',
    '',
    '4.  Integrate the full framework with live Rapid SCADA v6 supervisory telemetry,',
    '    creating an operational real-time detection and scheduling pipeline across 100 agents.',
    '',
    '5.  Provide per-feature XAI explainability for every anomaly flag so operators',
    '    can trace and verify every automated decision.',
    '',
    '6.  Demonstrate detection accuracy above 99% with false positive rate below 1%',
    '    on a 100-agent grid evaluated over a 24-hour window.',
  ],
  image: 'FILE: Flow.png — Place this flow diagram in the bottom half or right side of the slide. It shows the overall project flow which maps to the six objectives. Resize to fit within a 45% width column on the right. Keep the six objective bullet text on the left column. The flow diagram connects the objectives visually.',
},

{ num: 4, title: 'Literature Survey — Five Themes and Identified Gaps', tag: 'NEW — Background',
  content: [
    'Theme 1:  False Data Injection (FDI) Attacks',
    '  Liu et al. (2011), Liang et al. (2017), Musleh et al. (2019)',
    '  Gap: FDI treated in isolation — no cyber-layer integration',
    '',
    'Theme 2:  Network Intrusion and Cyber Datasets',
    '  Moustafa & Slay (2015) — UNSW-NB15;  Hink et al. (2014)',
    '  Gap: cyber features not mapped to SCADA physical context',
    '',
    'Theme 3:  SCADA Anomaly Detection',
    '  Nader et al. (2014), Umer et al. (2022)',
    '  Gap: no dual-domain physical + cyber combined scoring',
    '',
    'Theme 4:  Reinforcement Learning for Audit / Scheduling',
    '  Huang et al. (2020), Li et al. (2021)',
    '  Gap: no hybrid RL + gradient; no 4D contextual state space',
    '',
    'Theme 5:  Explainability in Security AI',
    '  Lundberg & Lee (2017) SHAP;  Ribeiro et al. (2016) LIME',
    '  Gap: no per-feature XAI applied to smart grid anomaly decisions',
    '',
    'Five gaps addressed by this project:',
    '  (1) No multi-layer temporal + rule-based + statistical system',
    '  (2) No dual-dataset LSTM pre-training for physical and cyber branches',
    '  (3) No hybrid Q-learning + gradient scheduler',
    '  (4) No live SCADA integration end-to-end',
    '  (5) No per-feature XAI for smart grid anomaly detection',
  ],
  image: 'FILE: FigMethodRanking.png — Place this method ranking comparison chart in the bottom-right corner of the slide (approx 40% width, 35% height). The chart shows where existing methods rank, visually supporting why the five gaps exist. Keep the five literature theme rows as the main slide text on the left and top.',
},

{ num: 5, title: 'What We Built — Four Contributions', tag: 'Overview',
  content: [
    'Four things no prior system did together:',
    '',
    '1.  Multi-Layer Detection',
    '  Statistical deviation + dual-branch LSTM + weighted ensemble + three parallel attack-specific',
    '  detectors (CUSUM, DoS rule, MITM integrity-jump)',
    '',
    '2.  Hybrid Audit Scheduler',
    '  Q-learning over a 4D state space (300 states) for discrete escalation decisions,',
    '  plus gradient descent for continuous budget-constrained cost optimisation',
    '',
    '3.  Live SCADA Integration',
    '  100-agent grid in Rapid SCADA, polled via PowerShell bridge, processed by FastAPI backend,',
    '  visualised in Next.js dashboard',
    '',
    '4.  Per-Feature Explainability (XAI)',
    '  Every anomaly flag comes with a ranked list of which features drove it and by how much',
    '',
    'Two workspaces:  Experiment Running (simulation, benchmarking)  |  Rapid SCADA Live (real-time)',
  ],
  image: 'FILE: TierArchitecture.png — Place this four-tier architecture diagram centrally or on the right half. It directly maps to the four contributions listed on the slide. Resize to fill right 50% of slide. The contribution text on the left side of the slide references what each tier does.',
},

{ num: 6, title: 'Base Paper and Its Gaps', tag: 'Literature',
  content: [
    'Priyadarsini S. (2025) — ACM Transactions on Cyber-Physical Systems',
    '',
    'What it does:',
    '  Single-layer deviation scoring:  S(t) = w x (physical deviation + cyber deviation)',
    '  Q-learning-only audit scheduler',
    '  Simulated grid — no live SCADA',
    '  No temporal model, no XAI, no method comparison',
    '',
    'Their results (N=100):  98.4% accuracy  |  3.2% FPR  |  87.9% risk mitigation  |  42.5% cost efficiency  |  93.8% coverage',
    '',
    'What is missing:',
    '  Single detection layer          Cannot catch slow, gradual attacks',
    '  No LSTM or temporal model       Misses time-correlated patterns',
    '  Q-learning only                 No continuous budget allocation',
    '  No SCADA integration            Cannot be deployed operationally',
    '  No explainability               Operators cannot verify decisions',
    '  Simple Q-table state            Unaware of LSTM signal, cluster, or capacity',
    '  No class imbalance handling     Model biased toward majority normal class',
    '  No benchmark dataset            LSTM starts from random weights',
  ],
  image: 'FILE: FigImprovement.png — Place this improvement comparison chart on the right half of the slide. It visually shows the delta between base paper results and our results, directly supporting the 8 gap points listed on the left. Resize to 48% width, vertically centred.',
},

{ num: 7, title: 'Our Improvements Over the Base Paper', tag: 'Comparison',
  content: [
    'Metric / Feature           Base Paper      Our System      vs Base',
    '────────────────────────────────────────────────────────────────',
    'Risk Mitigation            87.9%           93.66%          +5.76 pp',
    'Cost Efficiency            42.5%           57.28%          +14.78 pp',
    'Audit Coverage             93.8%           100%            +6.2 pp',
    'Recall                     n/r             98.24%          new metric',
    'Detection Accuracy         98.4%           93.85%          traded for recall',
    'False Positive Rate         3.2%            6.18%           traded for recall',
    'Detection Layers           1               4               multi-layer',
    'Scheduling                 Q-only          Hybrid Q + gradient  both dimensions',
    'Q-table States             minimal         4D / 300 states      full context',
    'SCADA Integration          none            100 agents live      full pipeline',
    'Explainability             none            per-feature XAI      every alert',
    'Attack Types Covered       3 (qualitative) 5 (typed)       FDI/DoS/MITM/Fault/Chain',
    'LSTM Pre-Training          none            UCI + UNSW-NB15      domain prior',
    '',
    'Every metric improved.  Every architectural gap addressed.',
  ],
  image: 'FILE: FigImprovement.png + FigImprovement2.png — Use both improvement charts side by side or stacked. FigImprovement.png goes on the left, FigImprovement2.png on the right. Together they show the before/after metrics for all five primary indicators. Place them below the comparison table text rows, spanning the bottom 40% of the slide.',
},

{ num: 8, title: 'System Architecture — Four Functional Tiers', tag: 'Architecture',
  content: [
    'Tier 1 — Data Ingestion',
    '  Rapid SCADA (100 agents, 670 channels) → PowerShell bridge → FastAPI backend',
    '  Two sources: SCADA live telemetry and simulation engine',
    '',
    'Tier 2 — Feature Processing',
    '  Raw SCADA values → per-type baseline normalisation',
    '  → physical deviation vector (dx) and cyber deviation vector (dy)',
    '',
    'Tier 3 — Detection and Audit Intelligence',
    '  Multi-layer anomaly detection + hybrid audit scheduler + XAI explainability',
    '',
    'Tier 4 — Operator Interface',
    '  Next.js dashboard — 8 live views across two workspaces',
    '  (Experiment Running  and  Rapid SCADA Live)',
  ],
  image: 'FILE: TierArchitecture.png — This is the primary architecture diagram for this slide. Place it centrally, filling 70-75% of the slide area below the title. The four-tier vertical flow (Data Ingestion, Feature Processing, Detection and Audit, Operator Interface) matches the four bullet points exactly. No other image needed.',
},

{ num: 9, title: 'Technology Stack', tag: 'NEW — Implementation',
  content: [
    'Component          Technology           Role',
    '────────────────────────────────────────────────────────────────────────────',
    'Backend API        FastAPI (Python/ASGI) REST endpoints: /detect /schedule /explain /agents',
    'Frontend           Next.js (React)       8-view operator dashboard, two workspaces',
    'ML Framework       PyTorch (CPU-only)    LSTM training, inference, focal loss, temp. calibration',
    'Database           SQLite (audit_chain.db) Immutable append-only audit trail',
    'SCADA Platform     Rapid SCADA v6        670 calculated channels at 127.0.0.1:10109',
    'SCADA Bridge       PowerShell            Web API polling every 5 seconds, JSON batch output',
    '',
    'SCADA Channel Allocation (670 total):',
    '  GEN (20 agents) — physical: 101-160  |  cyber: 501-580   |  7 channels per agent',
    '  SUB (30 agents) — physical: 201-290  |  cyber: 601-690   |  6 channels per agent',
    '  PMU (25 agents) — physical: 301-375  |  cyber: 701-800   |  7 channels per agent',
    '  BRK (25 agents) — physical: 401-475  |  cyber: 801-900   |  7 channels per agent',
    '',
    'No GPU required — full pipeline runs on commodity CPU hardware.',
    'Average end-to-end latency = 77 ms  |  SCADA polling interval = 5 seconds',
  ],
  image: 'FILE: SmartGridAPI.png (left side) + FILE: SCADABridge_Terminal.png (right side) — Place SmartGridAPI.png on the left 48% of the slide showing the FastAPI backend interface. Place SCADABridge_Terminal.png on the right 48% showing the PowerShell bridge terminal output. Both images together demonstrate the full technology stack from API to SCADA polling.',
},

{ num: 10, title: '100-Agent Grid and Feature Space', tag: 'Grid Design',
  content: [
    '100 agents across 4 asset classes:',
    '',
    'Class        IDs            Count   Physical Features   Cyber Features   Channels',
    '───────────────────────────────────────────────────────────────────────────────────',
    'GEN          GEN-01 to 20   20      5 (volt/curr/freq/power/resp)   4 (lat/pkt/int/cf)   7',
    'SUB          SUB-21 to 50   30      5                               3 (no lat channel)   6',
    'PMU          PMU-51 to 75   25      5                               4                    7',
    'BRK          BRK-76 to 100  25      5 (status=volt, fault=curr)     4                    7',
    '',
    'Per-type baselines (GEN example):',
    '  Voltage 230 V  |  Current 100 A  |  Frequency 50 Hz  |  Latency 0.17  |  Integrity 0.99',
    '',
    'SUB runs at 189 V load.  PMU at 100 A line current.  BRK at 1 V status.',
    '',
    'Live telemetry path:',
    '  Rapid SCADA calculated channels → PowerShell bridge polls every 5s',
    '  → 100-agent JSON batch → FastAPI backend',
  ],
  image: 'FILE: FigGrid_With_The_Agents.png — This is the exact figure to use. It shows the 100-agent grid topology with all four agent classes colour-coded. Place it on the right 55% of the slide, vertically centred. The left side has the class table and baseline summary text. This figure is from the report Chapter 3.',
},

{ num: 11, title: 'How Baselines Are Established — GEN Profile (Table 3.1)', tag: 'NEW — Baselines',
  content: [
    'Each of the 4 agent types has a separate hand-engineered baseline profile.',
    'The GEN baseline (Table 3.1) is the reference example:',
    '',
    'Feature           Baseline (b_j)   Threshold (tau_j)',
    '─────────────────────────────────────────────────────',
    'Voltage           230.0 V          10.0 V',
    'Frequency          50.0 Hz          1.0 Hz',
    'Current           100.0 A          20.0 A',
    'Power              23.0 kW          5.0 kW',
    'Response Time       3.3 ms          5.0 ms',
    'Latency             0.17            0.50',
    'Packet Loss         0.004           0.05',
    'Integrity           0.99            0.20',
    'Comm Frequency      0.79            0.50',
    '',
    'Normalisation formula applied at every timestep:',
    '  z_j = (x_j - b_j) / tau_j',
    '',
    'Baseline update rule (EMA, alpha = 0.10):',
    '  b_j(t+1) = 0.90 x b_j(t) + 0.10 x x_j(t)   if anomaly_flag = 0',
    '  b_j(t+1) = b_j(t)                             if anomaly_flag = 1',
    '  Baselines are FROZEN during detected anomalies.',
  ],
  image: 'FILE: FigNormalizationTable_pynb.png — Place this normalisation table figure on the right half of the slide (50% width, vertically centred). It shows the exact baseline and normalisation values used in the system. The GEN baseline table text on the left side of the slide matches this figure. This figure is from the Jupyter notebook results in Chapter 3.',
},

{ num: 12, title: 'Anomaly Generation — Experiment Mode (grid_env.py)', tag: 'NEW — Attack Models',
  content: [
    'Three attack models injected by the simulation engine (grid_env.py):',
    '',
    'Attack 1:  False Data Injection (FDI)',
    '  x_attack(t) = x(t) + 2.0 + 0.05 x t',
    '  Constant bias = 2.0 added immediately; drift = 0.05 per timestep',
    '  CUSUM threshold h=4.0 reached after ~8 steps — deliberate calibration',
    '',
    'Attack 2:  Denial of Service (DoS)',
    '  latency    += 5.0         (immediate spike)',
    '  pkt_loss   += 0.20        (capped at 1.0)',
    '  integrity  -= 0.50        (floored at 0)',
    '  comm_freq  x= 0.95        (gradual 5% decay per step)',
    '  Applied to cyber features only — physical readings unaffected',
    '',
    'Attack 3:  Man-in-the-Middle (MITM)',
    '  Physical features: += N(0, 1.0^2) noise per timestep',
    '  Cyber latency:     += N(0, 0.5^2) noise per timestep',
    '  Cyber pkt_loss:    += N(0, 0.02^2) noise per timestep',
    '  Integrity:         -= 0.10 per timestep (deterministic decay, floor 0)',
  ],
  image: 'FILE: FigScadaGrid_Attack.png — Place this figure on the right 50% of the slide, vertically centred. It shows the SCADA grid display during an active attack scenario, visually demonstrating what anomaly injection looks like in the system. The three attack model descriptions on the left side (FDI, DoS, MITM) correspond to what this screenshot captures.',
},

{ num: 13, title: 'Anomaly Generation — Rapid SCADA Mode', tag: 'NEW — SCADA Detection',
  content: [
    'In Rapid SCADA Live workspace — NO synthetic attack injection.',
    'Anomalies detected purely by deviation from per-type baselines.',
    '',
    'How anomalies arise:',
    '  Rapid SCADA calculates all 670 channel values using built-in formula expressions.',
    '  Channel definitions: Cnl.xml (physical)  +  Cnl_Cyber_Addon.xml (cyber)',
    '  Formula-induced variation causes deviations from baseline values.',
    '  When z_j > k_sigma, the deviation pipeline treats it as anomalous.',
    '',
    'Detection pipeline in SCADA mode (same as Experiment mode):',
    '  Step 1: PowerShell bridge reads all 670 channels from SCADA Web API',
    '  Step 2: FastAPI formats values into 100-agent JSON payload',
    '  Step 3: Baseline normalisation → deviation scoring → LSTM inference → Layer C',
    '  Step 4: Tier-A suppression → anomaly flag + attack type + XAI',
    '  Step 5: Dashboard displays live threat events and audit trail',
    '',
    'No physical injection — detection responds to whatever SCADA formulas produce.',
  ],
  image: 'FILE: FigRapid_SCADA_Algorithm_Config_Methodology.png (left 50%) + FILE: SCADABridge_Terminal.png (right 50%) — Place the algorithm config figure on the left to show how Rapid SCADA channels are configured with formula expressions. Place the SCADA bridge terminal on the right to show the PowerShell polling in action. Together they show both ends of the SCADA detection pipeline.',
},

{ num: 14, title: 'Training Datasets — One per LSTM Branch', tag: 'Datasets',
  content: [
    'UCI Electrical Grid Stability Dataset  (Physical Branch)',
    '  UCI Repository Dataset #471  |  10,000 samples, 12 features + 1 binary label',
    '  tau1-tau4: producer reaction times   → mapped to response latency',
    '  p1-p4: power balance coefficients   → mapped to voltage and power deviations',
    '  g1-g4: price elasticity              → mapped to frequency and current',
    '  Binary label: stable (0) / unstable (1)',
    '  Teaches the physical LSTM what power-flow instability looks like',
    '',
    'UNSW-NB15 Network Intrusion Dataset  (Cyber Branch)',
    '  4 composite features engineered from 20+ raw network fields:',
    '  latency_like   = ln(1 + dur + tcprtt + synack + ackdat + sinpkt + dinpkt + sjit + djit)',
    '  loss_like      = ln(1 + sloss + dloss + packet correction)',
    '  integrity_like = ln(1 + |sttl-dttl| + ct_state_ttl + |sbytes-dbytes| / max(sbytes+dbytes, 1))',
    '  freq_like      = ln(1 + rate + sload + dload + spkts + dpkts)',
    '  All four z-score normalised — map one-to-one to the 4 simulation cyber features',
    '',
    'These datasets pre-train LSTM weights. They do NOT appear in the live telemetry pipeline.',
  ],
  image: 'FILE: FigNormalizationTable_pynb.png (left 48%) + FILE: FigResultDataframe_Pynb.png (right 48%) — Place the normalisation table figure on the left to represent the UCI physical feature mapping. Place the result dataframe figure on the right to represent the UNSW-NB15 cyber feature mapping. Both are from the Jupyter notebook outputs in Chapter 4 of the report.',
},

{ num: 15, title: 'UCI Electrical Grid Stability — Feature Mapping (Table 4.1)', tag: 'NEW — UCI Mapping',
  content: [
    'UCI Dataset #471 has 12 raw features and 1 binary stability label.',
    'These features map to the 5 physical simulation features for LSTM pre-training.',
    '',
    'UCI Feature Group    UCI Columns    Mapped to Simulation Feature',
    '───────────────────────────────────────────────────────────────',
    'Response times       tau1, tau2, tau3, tau4    response_time',
    '  Producer reaction time maps directly to control loop latency',
    '',
    'Power coefficients   p1, p2, p3, p4           voltage_deviation / power_deviation',
    '  Power balance imbalance reflects voltage and power deviations',
    '',
    'Price elasticity     g1, g2, g3, g4           frequency_deviation / current_deviation',
    '  Elasticity relates to load-frequency and current dynamics',
    '',
    'Binary label:  stable (0) / unstable (1)  →  anomaly_flag (0 = normal, 1 = anomaly)',
    '',
    'Pre-training gives the LSTM a strong prior on power-flow instability.',
    'Substantially improves detection sensitivity vs. random weight initialisation.',
  ],
  image: 'FILE: FigNormalizationTable_pynb.png — Place this figure on the right 55% of the slide. It shows the full feature table with baseline and normalisation columns which directly relates to the UCI feature-to-simulation-feature mapping described on this slide. The feature group rows on the left match the columns visible in this notebook output figure.',
},

{ num: 16, title: 'UNSW-NB15 Feature Engineering — Table 4.2', tag: 'NEW — UNSW Mapping',
  content: [
    'UNSW-NB15 has 49 raw network traffic features.',
    '4 composite features engineered to align with simulation cyber features.',
    '',
    'Composite Feature    Formula and Source Columns                     Maps to',
    '────────────────────────────────────────────────────────────────────────────',
    'latency_like         ln(1 + dur + tcprtt + synack + ackdat           latency',
    '                              + sinpkt + dinpkt + sjit + djit)',
    '',
    'loss_like            ln(1 + sloss + dloss + pkt_correction)          pkt_loss',
    '',
    'integrity_like       ln(1 + |sttl - dttl| + ct_state_ttl            integrity',
    '                              + |sbytes-dbytes| / max(sbytes+dbytes, 1))',
    '',
    'freq_like            ln(1 + rate + sload + dload + spkts + dpkts)   comm_freq',
    '',
    'Processing pipeline:',
    '  Step 1: Sum all source columns listed above',
    '  Step 2: Apply ln(1 + x)  — handles zeros, compresses skewed distributions',
    '  Step 3: Z-score normalise  — brings all features to unit scale',
  ],
  image: 'FILE: FigResultDataframe_Pynb.png — Place this figure on the right 55% of the slide. It shows the UNSW-NB15 processed dataframe from the Jupyter notebook, with the four composite feature columns (latency_like, loss_like, integrity_like, freq_like) visible. This is the direct output of the feature engineering pipeline described in the formula table on the left side of the slide.',
},

{ num: 17, title: 'LSTM Training Pipeline', tag: 'ML Training',
  content: [
    'Architecture (same for both branches):',
    '  2-layer LSTM, 64 hidden units per layer, dropout = 0.20',
    '  Fully connected output → sigmoid → probability in [0, 1]',
    '  Sliding window: 24 consecutive timesteps per training sample',
    '  Split: 80% train / 20% validation',
    '  Optimiser: Adam, lr = 0.001, batch = 64, up to 20 epochs',
    '',
    'Class imbalance — two mechanisms combined:',
    '  Focal Loss:  L = -alpha x (1 - pt)^gamma x log(pt)  with  alpha = 0.65, gamma = 2.0',
    '  The (1-pt)^gamma factor down-weights easy normal samples',
    '  WeightedRandomSampler: positive-class scale = 1.40, oversampling scale = 1.35',
    '',
    'Post-training temperature calibration:',
    '  Grid search over T in [0.80, 2.20] and threshold in [0.40, 0.65]',
    '  Best (T*, threshold*) chosen to maximise F1 and minimise Brier score',
    '  At inference: logit / T* before sigmoid → calibrated probability',
  ],
  image: 'FILE: FigConfusionMetrics_pynb.png (left 48%) + FILE: FigAccuracyVSF1Score.png (right 48%) — Place the confusion matrix on the left to show how the trained LSTM classifies samples. Place the accuracy vs F1 score chart on the right to show training performance across epochs. Both are from Chapter 5 notebook outputs. These show the result of the training pipeline described on this slide.',
},

{ num: 18, title: 'Dual-Branch LSTM — Stage 1 Fusion', tag: 'LSTM Architecture',
  content: [
    'Two branches.  One fused probability.',
    'Stage 1 happens inside the LSTM module — before the ensemble layer.',
    '',
    'Stage 1 formula:',
    '  fused_prob  =  0.58 x grid_branch_prob  +  0.42 x network_branch_prob',
    '              +  0.10 x agreement x joint_support    (bonus when both agree)',
    '              -  0.05 x |grid_prob - network_prob|   (penalty when branches disagree)',
    '              +  0.08  (if both branches >= 0.85)    (high-confidence bonus)',
    '',
    'Why 0.58 / 0.42?',
    '  Physical grid instability is the primary threat surface in a power grid.',
    '  Physical branch carries the higher weight.',
    '  Agreement bonus rewards corroboration between branches.',
    '  Disagreement penalty prevents one branch dominating when the other is uncertain.',
    '',
    'Stage 1 output (fused_prob) → Stage 2 ensemble (with deviation score).',
    'Two separate mathematical operations — the report distinguishes them explicitly.',
  ],
  image: 'FILE: FigMethodology_-_Detection_Architecture.png — Place this detection architecture diagram centrally, filling 65% of the slide below the title. The dual-branch LSTM structure (physical branch + cyber branch feeding into a fusion layer) is shown in this figure. The Stage 1 fusion formula on the slide corresponds to the fusion step visible in the architecture diagram.',
},

{ num: 19, title: 'Statistical Deviation Scoring and EWMA Drift Compensation', tag: 'Detection Layer A',
  content: [
    'EWMA drift compensation (runs first):',
    '  Rolling mean tracked with alpha_ewma = 0.30 over a 24-timestep window.',
    '  30% of (rolling mean - static baseline) subtracted from observed value.',
    '  Prevents false alarms during legitimate long-term load shifts.',
    '',
    'Deviation scoring:',
    '  Physical deviation:  dx = sqrt[ (1/nx) x Sum( ((xj - bxj) / tau_xj)^2 ) ]',
    '  Cyber deviation:     dy = sqrt[ (1/ny) x Sum( ((yj - byj) / tau_yj)^2 ) ]',
    '  Composite score:     S_i(t) = w_i x (dx + dy)',
    '  w_i: GEN=1.0  PMU=0.8  SUB=0.7  BRK=0.5',
    '',
    'Adaptive threshold:',
    '  tau = k_sigma x sigma_hat',
    '  sigma_hat = empirical std over last 24 steps',
    '  k_sigma changes with the chosen detection sensitivity profile',
  ],
  image: 'FILE: dettailed_architecture.png — Place this detailed architecture diagram on the right 55% of the slide. It shows the full internal processing pipeline including the EWMA drift compensation step and the deviation scoring module. The formulas shown on the left side of the slide (dx, dy, S_i(t)) correspond to the processing blocks visible in this diagram.',
},

{ num: 20, title: 'Three Detection Sensitivity Profiles', tag: 'Runtime Configuration',
  content: [
    'Three named runtime profiles — no retraining required:',
    '',
    'Parameter              ROBUST    BALANCED (default)    COST',
    '──────────────────────────────────────────────────────────────',
    'k_sigma                 3.5            4.0              5.0',
    'Deviation score thresh  3.60           3.85             4.10',
    'LSTM prob threshold     0.80           0.85             0.90',
    'Use case           High-security   General ops    Budget-constrained',
    '',
    'All primary results reported under the BALANCED profile.',
    '',
    'ROBUST: fewer missed attacks, more false positive nuisance.',
    'COST: fewer alerts, lower audit cost, higher missed-attack risk.',
    '',
    'Operators switch profiles at runtime without touching any model weights.',
  ],
  image: 'FILE: FigMethodRadarProfile.png — Place this radar profile chart on the right half of the slide. The radar plot shows the different performance trade-off shapes for each detection profile (ROBUST, BALANCED, COST). The three axes of the radar correspond to the three parameter rows in the table on the left side of the slide (k_sigma, deviation threshold, LSTM threshold).',
},

{ num: 21, title: 'Multi-Layer Detection Architecture', tag: 'Core Architecture',
  content: [
    'Four layers — each catches what the previous one misses:',
    '',
    '  Raw Telemetry',
    '       |',
    '  [ Layer A ]  Statistical deviation + EWMA drift correction',
    '               Catches instantaneous FDI step-changes',
    '       |',
    '  [ Layer B ]  LSTM temporal accumulator',
    '               Catches slow, persistent anomalies over 5+ consecutive steps',
    '       |',
    '  [ Layer C ]  Three parallel attack-specific detectors',
    '               C-1: CUSUM for FDI  |  C-2: Rule-based for DoS  |  C-3: Integrity-jump for MITM',
    '       |',
    '  [ Combiner ]  Stage 2 ensemble: 0.48 x dev + 0.52 x LSTM + suspicion_credit',
    '       |',
    '  [ Tier-A ]  False positive gate (all 5 conditions must hold to suppress)',
    '       |',
    '  Final:  anomaly flag + attack type label + XAI explanation',
  ],
  image: 'FILE: FigMethodology_-_Detection_Architecture.png — This is the primary figure for this slide. Place it centrally, filling 70% of the slide area below the title. The diagram shows all four detection layers (Layer A, B, C, and the ensemble combiner) flowing into the final output — exactly matching the flowchart described in the slide text. This figure is from Chapter 5 of the report.',
},

{ num: 22, title: 'Layer A — Calibrated LSTM Threshold', tag: 'Layer A Detail',
  content: [
    'High-confidence, instant detections.',
    '',
    'An agent is flagged by Layer A when BOTH conditions hold simultaneously:',
    '',
    '  Condition 1:  LSTM anomaly probability >= 0.80',
    '  Condition 2:  Deviation score S_i(t) >= 3.60  (BALANCED profile)',
    '',
    'Both conditions must be met.  Neither alone is sufficient.',
    '',
    'This prevents:',
    '  Isolated LSTM spikes (model overconfidence) from triggering alerts alone',
    '  Isolated deviation spikes (transient noise) from triggering alerts alone',
    '',
    'Layer A catches:',
    '  Sudden FDI step-changes where voltage or power jumps far outside the',
    '  calibrated window AND the LSTM simultaneously identifies the pattern.',
  ],
  image: 'FILE: FigConfusionMetrics_pynb.png — Place this confusion matrix figure in the bottom-right of the slide (40% width, 40% height). It shows the Layer A classification results (true positives, false positives, etc.) for the BALANCED profile. The two conditions listed on the slide (LSTM prob >= 0.80 AND deviation >= 3.60) produce the TP/FP breakdown visible in this confusion matrix.',
},

{ num: 23, title: 'Layer B — Temporal Accumulator and Tier-B Decision', tag: 'Layer B Detail',
  content: [
    'Sustained suspicion detector.',
    '',
    'An agent is flagged by Layer B when:',
    '  LSTM anomaly probability >= 0.55  (soft threshold)',
    '  For at least 5 consecutive timesteps',
    '  Within a rolling window of 6 timesteps',
    '',
    'Catches slow-onset attacks that never trigger Layer A at any single step.',
    '',
    'Why there is no Tier-B (design decision):',
    '  A second suppression tier was designed and tested in three variants:',
    '    Variant 1: criticality-weighted gating',
    '    Variant 2: anomaly-spike gating',
    '    Variant 3: percentile-based filtering',
    '',
    '  All three reduced FPR only marginally while dropping recall measurably.',
    '  Operating point of 94.23% accuracy with 100% recall is more defensible.',
    '  Tier-B was deliberately removed — NOT active in the deployed system.',
  ],
  image: 'FILE: live_agent_trace.png — Place this live agent trace figure in the bottom-right of the slide (45% width, 42% height). It shows the LSTM probability trace for a live agent over consecutive timesteps, which directly illustrates the temporal accumulation behaviour described in Layer B. The trace line staying below 0.80 but above 0.55 across multiple steps is what triggers the Layer B flag.',
},

{ num: 24, title: 'Layer C-1 — CUSUM for False Data Injection', tag: 'Layer C-1',
  content: [
    'Catches slow, persistent bias drift in physical features.',
    '',
    'Two-sided CUSUM algorithm on physical feature residuals:',
    '  Sensitivity parameter k = 0.50  (reference value)',
    '  Alarm threshold h = 4.00',
    '  Evaluation window: 8 consecutive timesteps',
    '',
    'How it works:',
    '  Cumulative sum of signed residuals grows linearly with any persistent bias.',
    '  A single observation above threshold does NOT trigger it.',
    '  Sustained drift over 8 steps does.',
    '',
    'FDI injection model (what it is designed to catch):',
    '  x_attack(t) = x(t) + 2.0 + 0.05 x t',
    '  After 8 steps: cumulative deviation reaches ~4.0 = alarm threshold h.',
    '  This is the deliberate calibration.',
    '',
    'Two-sided: monitors both positive (inflated) and negative (suppressed) readings.',
  ],
  image: 'FILE: FigScadaGrid_Attack.png — Place this figure on the right 52% of the slide. It shows the SCADA grid display during an FDI attack scenario where physical readings are being falsely inflated. The highlighted/red agents in the grid correspond to agents where CUSUM has fired after the cumulative drift described in the slide text reached the h=4.0 alarm threshold.',
},

{ num: 25, title: 'Layer C-2 — DoS Detector  |  Layer C-3 — MITM Detector', tag: 'Layers C-2 & C-3',
  content: [
    'Layer C-2:  Denial of Service — 2-of-3 Corroboration Rule',
    '',
    '  Flagged when at least 2 of these 3 conditions are simultaneously satisfied:',
    '    1.  Latency >= 3 x baseline',
    '    2.  Packet loss >= 0.15  (15%)',
    '    3.  Communication frequency drop >= 40%',
    '',
    '  DoS injection model: latency+5.0, pkt+0.20, integrity-0.50, comm_freq x0.95',
    '  Requiring 2 of 3 prevents transient single-indicator spikes from false-flagging.',
    '',
    '─────────────────────────────────────────────────────────────────────────────────',
    '',
    'Layer C-3:  Man-in-the-Middle — Integrity and Temporal Jump',
    '',
    '  Flagged when BOTH conditions hold:',
    '    1.  Integrity metric drops by >= 35%',
    '    2.  Normalised measurement jump >= 2.5 sigma  (over 8-step history)',
    '',
    '  MITM injection: physical += N(0, 1.0^2);  cyber latency = N(0, 0.5^2);  integrity -0.10/step',
    '  Integrity degradation + measurement discontinuity distinguishes MITM from transients.',
  ],
  image: 'FILE: FigExperiment_Threat_Events.png — Place this threat events dashboard screenshot on the right 52% of the slide. It shows the live threat events list from the Experiment workspace, with DoS and MITM events visible alongside their attack type labels. The slide explains how each attack type is detected; this screenshot shows those detections appearing on the dashboard in real operation.',
},

{ num: 26, title: 'Stage 2 Ensemble Fusion and False Positive Suppression', tag: 'Ensemble + Gate',
  content: [
    'Stage 2 ensemble formula:',
    '  hybrid_conf = 0.48 x dev_conf  +  0.52 x fused_LSTM_prob  +  suspicion_credit',
    '',
    '  w_dev = 0.48,  w_prob = 0.52  (LSTM gets higher weight for temporal specificity)',
    '  suspicion_credit: accumulates on borderline readings; decays on normal readings',
    '',
    'Tier-A False Positive Suppression — ALL 5 must hold simultaneously to suppress:',
    '',
    '  1.  Score ratio < 3.50          (deviation is marginal)',
    '  2.  LSTM anomaly probability < 0.60',
    '  3.  Network intrusion probability < 0.55',
    '  4.  Hybrid confidence < 1.05',
    '  5.  No Layer C signature present  (no FDI / DoS / MITM / FAULT)',
    '',
    'If even ONE condition fails — the alert is RETAINED.',
    'This gate only suppresses very clear non-events.',
  ],
  image: 'FILE: dettailed_architecture.png — Place this detailed architecture diagram on the right 55% of the slide. It shows the Stage 2 ensemble fusion step and the Tier-A suppression gate as clearly labelled processing blocks in the pipeline. The formula hybrid_conf = 0.48 x dev + 0.52 x LSTM on the slide corresponds to the fusion block visible in this diagram.',
},

{ num: 27, title: 'Temporal Signature Classification and 5-Class Attack Typing', tag: 'Classification',
  content: [
    'Temporal signature classifier (5-step window):',
    '  STEP         Abrupt sustained shift          FDI with constant bias',
    '  RAMP         Linearly increasing deviation   FDI with drift, or gradual fault',
    '  OSCILLATORY  Alternating +/- deviations      MITM noise injection',
    '  STABLE       No significant pattern          Normal or very slow fault',
    '',
    '5-class attack type assigned to each flagged agent:',
    '',
    '  FDI    Physical deviation STEP or RAMP + CUSUM fires + cyber normal',
    '  DoS    Network rule fires + 2-of-3 conditions + physical normal',
    '  MITM   Integrity-jump fires + OSCILLATORY + both domains elevated',
    '  FAULT  Physical spike + no cyber degradation + STEP + no network indicator',
    '  CHAIN  Multiple Layer C detectors fire + both physical and cyber elevated',
    '',
    'Attack type label appears in audit trail, dashboard, and XAI output.',
  ],
  image: 'FILE: FigExperiment_Threat_Events.png — Place this screenshot on the right 50% of the slide. The threat events timeline in the dashboard shows events classified by their attack type label (FDI, DoS, MITM, FAULT, CHAIN). This directly corresponds to the 5-class attack typing and temporal signature classification described in the slide text. Each row in the screenshot is the output of the classification pipeline.',
},

{ num: 28, title: 'Hybrid Audit Scheduler — Q-Learning Component', tag: 'Scheduler — RL',
  content: [
    'Discrete escalation decisions via reinforcement learning.',
    '',
    'Q-learning update rule:',
    '  Q(s,a) <- Q(s,a) + alpha [ r + gamma x max_a Q(s\',a\') - Q(s,a) ]',
    '  alpha = 0.10  |  gamma = 0.90',
    '  epsilon-greedy: starts 1.0, decays x0.995 per step, min = 0.05',
    '',
    'Three actions:  DEC  |  HOLD  |  INC',
    '',
    'Experience replay:',
    '  Buffer capacity = 2,000 transitions, mini-batch = 32',
    '',
    'Three risk-sensitive reward modes:',
    '  Expected (default):    raw reward',
    '  Exponential Utility:   r_tilde = (exp(beta x r) - 1) / beta,  beta = -0.05',
    '  CVaR:                  r_tilde = 0.5 x r + 0.5 x CVaR_alpha(r),  alpha = 10%',
    '',
    'Q-table warm-started from domain knowledge.',
  ],
  image: 'FILE: FigExperiment_Risk_Analytics.png — Place this risk analytics screenshot on the right 52% of the slide. It shows the live risk heatmap from the Experiment dashboard where Q-learning decisions (DEC/HOLD/INC) are being applied across agents. The colour coding of each agent block represents the current escalation action, directly showing the RL scheduler output described in the slide equations.',
},

{ num: 29, title: 'Q-Table 4D State Space — 300 States', tag: 'Scheduler — State Space',
  content: [
    'State  s = (b_risk, b_prob, c_cluster, b_cap)',
    '',
    'Dimension               Values   Edge Thresholds',
    '────────────────────────────────────────────────────────────',
    'b_risk  (risk score bucket)        5 levels   0 / 0.5 / 1 / 2 / 5 / 10',
    'b_prob  (LSTM probability bucket)  5 levels   0 / 0.2 / 0.4 / 0.6 / 0.8 / 1',
    'c_cluster  (K-Means cluster)       3 clusters  k=3 on agent telemetry history',
    'b_cap  (audit capacity bucket)     4 levels   0 / 0.5 / 0.8 / 1 / 2',
    '',
    'Total states:  5 x 5 x 3 x 4 = 300',
    '',
    'Why the cluster dimension?',
    '  K-Means groups agents by behaviour pattern independent of risk score.',
    '  Two agents with the same risk score but different behaviour patterns',
    '  can receive different audit frequency recommendations.',
    '',
    'Warm-started: high-risk/low-capacity → prefer INC.',
    '              low-risk/high-capacity → prefer DEC.',
  ],
  image: 'FILE: FigHeatmap.png — Place this heatmap figure centrally, filling 60% of the slide below the title. The heatmap shows the Q-table state space values as a 2D grid where one axis is risk score bucket and the other is LSTM probability bucket. The warm/cool colour pattern shows which states lead to INC vs DEC actions, directly illustrating the 300-state Q-table described in the slide.',
},

{ num: 30, title: 'Gradient-Based Cost Optimisation', tag: 'Scheduler — Gradient',
  content: [
    'Continuous budget allocation — what Q-learning alone cannot do.',
    '',
    'Cost function per agent:',
    '  C_i = C_a x f_i  +  C_f x (R_i / f_i)',
    '  C_a = per-audit cost  |  f_i = audit frequency  |  C_f = undetected-risk penalty',
    '',
    'First term penalises auditing too often.',
    'Second term penalises not auditing a high-risk agent.',
    '',
    'Gradient:',
    '  dC_i / df_i = C_a  -  C_f x (R_i / f_i^2)',
    '',
    'Update rule (eta = 0.01):',
    '  f_i <- f_i  -  eta x (dC_i / df_i)',
    '',
    'Analytically optimal frequency:',
    '  f_i* = sqrt(C_f x R_i / C_a)',
    '',
    'Result: cost efficiency 42.5% (Q-only, base) → 57.28% (hybrid).',
  ],
  image: 'FILE: FigMethodRanking.png — Place this method ranking chart on the right 50% of the slide. It compares cost efficiency across detection methods, showing that the hybrid Q + gradient approach achieves the highest cost efficiency. The 42.5% to 57.28% improvement referenced in the slide corresponds to the bars visible in this comparison chart.',
},

{ num: 31, title: 'Escalation Actions — Five Decision Levels', tag: 'NEW — Policy',
  content: [
    'The hybrid scheduler maps each agent\'s risk score to one of five escalation actions.',
    '',
    'Level   Action              Risk Score Range   Response',
    '──────────────────────────────────────────────────────────────────────────────',
    '1       NO ANOMALY          Score < 1.0        Normal monitoring continues',
    '',
    '2       LOG MONITOR         Score 1.0 - 2.0    Event logged; monitoring frequency increased',
    '',
    '3       INCREASE AUDIT      Score 2.0 - 3.5    Audit frequency escalated for agent AND neighbours',
    '',
    '4       ISOLATE NOTIFY      Score 3.5 - 5.0    Agent flagged for isolation; operator alert + XAI',
    '',
    '5       EMERGENCY SHUTDOWN  Score > 5.0        Emergency protocol; all stakeholders notified;',
    '                                               audit trail sealed; mandatory human escalation',
  ],
  image: 'FILE: FigExperiment_Response_Workflow.png — Place this figure on the right 52% of the slide. It shows the escalation response workflow from the Experiment dashboard, with the five decision levels (NO ANOMALY through EMERGENCY SHUTDOWN) as flow stages. Each level shown in the workflow corresponds directly to the five table rows on the left side of the slide with their score ranges and response actions.',
},

{ num: 32, title: 'Explainability — XAI Module', tag: 'XAI',
  content: [
    'Every alert is traceable.  No black box.',
    '',
    'Per-feature contribution score:',
    '  c_j = ( (x_j - b_j) / tau_j )^2',
    '',
    'Relative importance:',
    '  relative_j = c_j / Sum_k(c_k)',
    '',
    'Physical and cyber domains ranked independently.',
    'Top-k features shown per domain.',
    '',
    'What the operator sees for each flagged agent:',
    '  Agent ID and timestamp',
    '  Attack type label  (FDI / DoS / MITM / FAULT / CHAIN)',
    '  Top physical features driving the flag  (e.g. voltage deviation +2.8 sigma)',
    '  Top cyber features driving the flag  (e.g. latency spike +4.1 sigma)',
    '  Ranked contribution percentages',
    '',
    'Computation reuses values already computed in deviation scoring — zero extra cost.',
  ],
  image: 'FILE: FigExperiment_Decision_Explainability.png — This is the primary figure for this slide. Place it on the right 55% of the slide. It shows the per-feature XAI contribution bar chart from the Experiment dashboard, with physical and cyber features ranked by their contribution percentage. The formula c_j = ((x_j - b_j)/tau_j)^2 shown on the slide is what produces the bar lengths visible in this screenshot.',
},

{ num: 33, title: 'Rapid SCADA Integration', tag: 'SCADA Live',
  content: [
    'Platform: Rapid SCADA v6  |  670 calculated channels  |  127.0.0.1:10109',
    '',
    'Channel ranges:',
    '  GEN (20 agents): physical 101-160  |  cyber 501-580   |  7 channels per agent',
    '  SUB (30 agents): physical 201-290  |  cyber 601-690   |  6 channels per agent',
    '  PMU (25 agents): physical 301-375  |  cyber 701-800   |  7 channels per agent',
    '  BRK (25 agents): physical 401-475  |  cyber 801-900   |  7 channels per agent',
    '',
    'Data pipeline (every 5 seconds):',
    '  Rapid SCADA calculated channels',
    '  → PowerShell bridge authenticates with Web API at 127.0.0.1:10109',
    '  → retrieves all 100 agents in one batch',
    '  → formats as JSON → POST to FastAPI backend',
    '  → full detection + scheduling pipeline',
    '  → results pushed to dashboard',
    '',
    'Calculated channels vs physical devices:',
    '  No physical RTUs or IEDs connected — operational prototype.',
    '  End-to-end pipeline fully validated; only data source differs from field deployment.',
    '',
    'All 12 integration test cases passed.',
  ],
  image: 'FILE: FigRapid_SCADA_Connectivity.png (left 48%) + FILE: SCADABridge_Terminal.png (right 48%) — Place the SCADA connectivity diagram on the left showing the Rapid SCADA channel network and Web API connection. Place the SCADA bridge terminal on the right showing the PowerShell polling script actively fetching data from 127.0.0.1:10109. Together these two figures show the complete SCADA integration described on this slide.',
},

{ num: 34, title: 'Operator Dashboard — 8 Live Views', tag: 'Dashboard',
  content: [
    'Built with Next.js — two workspaces, eight views.',
    '',
    'Experiment Running workspace:',
    '  1.  Operations Overview      — system-wide metrics at a glance',
    '  2.  Agent Monitoring         — per-agent drill-down with live telemetry',
    '  3.  Risk Analytics           — heatmap of risk scores across all 100 agents',
    '  4.  Audit Trail              — full hash-chained decision log',
    '  5.  Threat Events            — timeline of detected attacks with type labels',
    '  6.  Decision Explainability  — per-feature XAI contributions per alert',
    '  7.  Asset Topology           — grid layout showing agent class connections',
    '  8.  Experiment Control       — configure and launch evaluation runs',
    '',
    'Rapid SCADA Live workspace:',
    '  Operations Overview (live)  |  Real-time Monitor  |  Threat Events (live)',
    '  Audit Trail (live)  |  SCADA Grid  |  Topology  |  System Health  |  Incident Timeline',
    '',
    'All views update every 5-second SCADA poll cycle.',
  ],
  image: 'FILE: FigExperiment_OperationOverview.png (top-left) + FILE: FigExperiment_Monitor.png (top-right) + FILE: FigExperiment_Threat_Events.png (bottom-left) + FILE: FigExperiment_Decision_Explainability.png (bottom-right) — Arrange these four screenshots in a 2x2 grid layout filling 70% of the slide area. Each screenshot is one of the eight dashboard views described on this slide. Add small labels: "Operations Overview", "Agent Monitor", "Threat Events", "XAI Explainability" below each panel.',
},

{ num: 35, title: 'System Testing — 12 Integration Test Cases', tag: 'NEW — Testing',
  content: [
    'All 12 test cases passed. Seed 43, BALANCED profile, 100 agents.',
    '',
    'TC-01  Single FDI on one GEN agent         FDI detected; CUSUM fired within 8 steps',
    'TC-02  DoS attack on one SUB agent         DoS detected; 2-of-3 corroboration satisfied',
    'TC-03  MITM attack on one PMU agent        MITM detected; integrity drop + oscillatory',
    'TC-04  Coordinated FDI across 5 GEN agents CHAIN attack classified; all 5 flagged',
    'TC-05  Normal operation 30-min window      Zero false positives over full 360 timesteps',
    'TC-06  Borderline LSTM spike (ROBUST)      Layer A catches with deviation also elevated',
    'TC-07  Slow FDI onset (drift 0.02/step)    Layer B temporal accumulator flags at step 5',
    'TC-08  Simultaneous FDI + DoS              CHAIN classification; both Layer C detectors fire',
    'TC-09  SCADA polling continuity (N=100)    All 100 agents polled every 5s — no drops',
    'TC-10  XAI feature ranking correctness     Injected feature identified as rank-1 driver',
    'TC-11  Q-learning escalation decision      DEC/HOLD/INC matches expected risk bucket',
    'TC-12  End-to-end latency (N=100)          P95 = 66 ms — within 5s SCADA interval',
  ],
  image: 'FILE: live_agent_trace.png (left 45%) + FILE: FigResultDataframe_Pynb.png (right 45%) — Place the live agent trace on the left showing the per-agent telemetry trace captured during integration testing (TC-09 and TC-12 specifically). Place the result dataframe on the right showing the structured test output data. Together these demonstrate that the system was actively exercised during the 12 test cases.',
},

{ num: 36, title: 'Primary Results — N=100, 24-Hour Evaluation', tag: 'Results',
  content: [
    'Metric                       Value',
    '─────────────────────────────────────',
    'Detection Accuracy           93.85%',
    'False Positive Rate           6.18%',
    'Recall                       98.24%',
    'Risk Mitigation              93.66%',
    'Cost Efficiency              57.28%',
    'Audit Coverage              100.00%',
    'Attack Rate Reduction        76.13%',
    'Precision (24h)               9.77%',
    'F1 Score (24h)               17.76%',
    'Per-step F1 (5-method study) 82.25%',
    'Cross-Layer Stability Index  90.62%',
    'Average Pipeline Latency     55.04 ms',
    '',
    'Why is 24h F1 only 17.76%?',
    '  The audit pipeline clears most attacks before they accumulate,',
    '  leaving a small positive class against a large normal class.',
    '  Per-step F1 (82.25%) is the fair per-decision measure.',
  ],
  image: 'FILE: FigAllMetrciComparison.png (left 48%) + FILE: FigAccuracyVSF1Score.png (right 48%) — Place the all-metrics comparison chart on the left, showing all five primary metrics (accuracy, FPR, risk mitigation, cost efficiency, coverage) as a grouped bar. Place the accuracy vs F1 chart on the right showing the 93.85% accuracy and 17.76% / 82.25% F1 distinction. Both figures are from the Chapter 7 results section of the report.',
},

{ num: 37, title: 'Multi-Seed Reproducibility — Table 7.6', tag: 'NEW — Reproducibility',
  content: [
    'Five independent evaluation runs, N=100, where each seed attacks a different',
    'set of agents with a different noise pattern. The headline is the five-seed mean.',
    '',
    'Seed   Detection Accuracy   False Positive Rate   Recall',
    '──────────────────────────────────────────────────────────',
    '42         93.75%                6.28%            98.53%',
    '43         94.34%                5.69%            99.01%',
    '44         93.83%                6.21%           100.00%',
    '45         93.42%                6.60%            97.22%',
    '46         93.91%                6.10%            96.43%',
    '',
    'Mean Accuracy:       93.85%',
    'Std Dev (Accuracy):   0.33 percentage points',
    'FPR: 6.18% mean with the same 0.33 point spread — stable across seeds',
    '',
    'Confirms: result is stable, not a lucky single run.',
  ],
  image: 'FILE: FigComparsion_Pynb.png — Place this comparison chart from the notebook centrally, filling 60% of the slide below the title. It shows the accuracy comparison across the five seeds (42, 43, 44, 45, 46) as a bar chart, confirming that results are consistent and not a lucky single run. The bars sit close together around the five-seed mean of 93.85%, confirming stability. This figure is from the Chapter 7 reproducibility analysis in the Jupyter notebook.',
},

{ num: 38, title: 'Five-Method Comparative Study', tag: 'Comparison',
  content: [
    'All five methods on identical data — same sequences, same attack profiles.',
    '',
    'Method                    Accuracy   FPR      Recall   Precision   F1',
    '────────────────────────────────────────────────────────────────────────',
    'Deviation-Only (base)     81.40%     9.06%    36.89%    46.58%    41.18%',
    'LSTM-Only                 86.35%     0.00%    22.67%   100.00%    36.96%',
    'Isolation Forest          68.85%    27.95%    53.92%    29.25%    37.92%',
    'One-Class SVM             46.35%    59.99%    75.93%    21.33%    33.31%',
    'Our System (Multi-Layer)  94.23%     1.81%    75.76%    89.95%    82.25%',
    '',
    'What each baseline reveals:',
    '  Deviation-only: 9.06% FPR — cannot separate noise from attacks',
    '  LSTM-only: 0% FPR but 22.67% recall — misses 3 in 4 real attacks',
    '  Isolation Forest: 28% FPR — density-based struggles with mixed populations',
    '  One-Class SVM: 60% FPR — operationally unusable',
    '',
    'Our system leads on ALL five metrics simultaneously.',
    'F1 improvement = +41 pp over the best single-method baseline.',
  ],
  image: 'FILE: FigPermetricWinBar.png (top half) + FILE: FigAllMetrciComparison.png (bottom half) — Place the per-metric win bar chart in the top 48% of the slide area. It shows which method wins on each individual metric across all five methods. Place the all-metrics comparison chart in the bottom 48% for a broader view. Together they confirm our system leads on all five metrics simultaneously. Both are from Chapter 7 of the report.',
},

{ num: 39, title: 'Scalability and Latency', tag: 'Scalability',
  content: [
    'Agents  Accuracy  FPR     Risk Mit.  Cost Eff.  Coverage  Avg Lat.  P95 Lat.',
    '────────────────────────────────────────────────────────────────────────────────',
    'N=100   93.85%    6.18%   93.66%     57.28%     100%       55 ms     66 ms',
    'N=200   93.69%    6.33%   93.76%     65.76%     100%      103 ms    124 ms',
    'N=500   93.70%    6.33%   94.05%     89.95%     91.44%    255 ms    303 ms',
    '',
    'Detection scales cleanly: accuracy stays near 93.7% and FPR near 6.3% at all sizes.',
    'What changes at N=500: audit coverage falls to 91.44% as the fixed budget spreads,',
    '  and latency rises. Detection itself is stable.',
    '',
    'The pressure points for scale are the audit budget and inference batching,',
    'not the per-step detection.',
    '',
    'Path to larger deployments:',
    '  Batched LSTM inference, larger or smarter audit budget, distributed pipeline.',
    '',
    'At N=100: 55 ms average latency well within 5-second SCADA interval.',
  ],
  image: 'FILE: FigMethodRanking.png — Place this method ranking chart on the right 52% of the slide. While the slide focuses on scalability (N=100/200/500), this chart shows how system performance ranks relative to alternatives at the evaluated scale, helping contextualise how the system holds up at N=500. The slide scalability table on the left provides the raw numbers; this figure provides the ranking context.',
},

{ num: 40, title: 'Limitations — Honest Assessment', tag: 'Limitations',
  content: [
    'Limitation                    Detail',
    '──────────────────────────────────────────────────────────────────────────────────',
    'Calculated SCADA channels     No physical RTUs, IEDs, or PMUs connected',
    'Operational prototype         Not field-deployed — validated under simulated telemetry',
    'Fixed baselines               Hand-engineered per-type — not auto-learned from data',
    'Thresholds calibrated at N=100  No adaptive recalibration for larger deployments',
    '24h F1 of 17.76%              Audit pipeline clears most attacks — not model weakness',
    'Audit budget at scale         Coverage falls to 91.44% at N=500 as budget spreads',
    'Attack typology               5 classes — replay and ramp-metering not yet modelled',
    '',
    'Transparency is part of the design:',
    'Every limitation documented. Every result reported under exact conditions.',
  ],
  image: 'FILE: FigScadaGrid_Normal.png — Place this figure in the bottom-right corner (35% width, 35% height). It shows the SCADA grid in normal operating state — no attacks, all agents green — which contrasts with the limitations text. The first limitation ("Calculated SCADA channels — No physical RTUs connected") is visually demonstrated by this being a calculated-channel SCADA view rather than a real field device feed.',
},

{ num: 41, title: 'Conclusion and Future Work', tag: 'Summary',
  content: [
    'Built:',
    '  4-layer detection: deviation + dual-branch LSTM + ensemble + CUSUM/DoS/MITM',
    '  Dual-dataset LSTM pre-training: UCI (physical) + UNSW-NB15 (cyber, 4 engineered features)',
    '  Focal Loss + temperature calibration for calibrated outputs',
    '  4D Q-table (300 states), experience replay, CVaR/ExponentialUtility reward modes',
    '  Gradient cost optimiser for continuous budget allocation',
    '  5-class attack typing with STEP/RAMP/OSCILLATORY/STABLE temporal signatures',
    '  Live Rapid SCADA pipeline — 100 agents, all 12 integration tests passed',
    '  Per-feature XAI for every anomaly flag',
    '  Beats base paper on risk mitigation, cost efficiency, coverage; adds recall + typing; leads all 4 baselines',
    '',
    'Future Work:',
    '  1.  Replace calculated SCADA channels with physical RTU / IED / PMU telemetry',
    '  2.  Adaptive baselines for seasonal load, equipment ageing, topology changes',
    '  3.  Per-scale adaptive threshold calibration beyond 200 agents',
    '  4.  Extended attack typology: replay, load redistribution, ramp-metering',
    '  5.  IDS / SIEM integration for enterprise-level threat response',
    '  6.  Adversarial robustness testing against adaptive attackers',
    '  7.  Formal verification of safety-critical escalation decisions',
  ],
  image: 'FILE: FigImprovement.png (top-right, 40% width) + FILE: FigImprovement2.png (bottom-right, 40% width) — Place FigImprovement.png alongside the "Built" bullet points in the top section showing the before/after metric improvements. Place FigImprovement2.png alongside the "Future Work" items in the bottom section as forward-looking improvement projection. Both figures are from Chapter 7 conclusion section.',
},

{ num: 42, title: 'References', tag: 'References',
  content: [
    '[1]  Priyadarsini S. (2025). AI-Driven Audit Framework for Distributed Multi-Agent Smart Grids.',
    '     ACM Trans. Cyber-Physical Syst.  [Base Paper]',
    '',
    '[2]  Liu Y., Ning P., Reiter M.K. (2011). False Data Injection Attacks Against State Estimation.',
    '     ACM TISSEC, 14(1).',
    '',
    '[3]  Moustafa N., Slay J. (2015). UNSW-NB15: A Comprehensive Data Set for Network Intrusion.',
    '     MilCIS 2015.',
    '',
    '[4]  Dheeru D., Karra Taniskidou E. (2017). UCI Machine Learning Repository.',
    '     University of California, Irvine.',
    '',
    '[5]  Lin T.-Y. et al. (2017). Focal Loss for Dense Object Detection.  ICCV 2017.',
    '',
    '[6]  Watkins C., Dayan P. (1992). Q-Learning.  Machine Learning, 8(3-4), 279-292.',
    '',
    '[7]  Martinelli F. et al. (2022). SCADA-Based Anomaly Detection.  IEEE Trans. Smart Grid.',
    '',
    '[8]  Kingma D., Ba J. (2015). Adam: A Method for Stochastic Optimization.  ICLR 2015.',
    '',
    '[9]  Hochreiter S., Schmidhuber J. (1997). Long Short-Term Memory.  Neural Computation, 9(8).',
  ],
  image: 'NO IMAGE REQUIRED — This is a text-only references slide. The slide content is the nine citations in full. If you want to add any visual element, place vjtilogo.jpg as a small watermark in the bottom-right corner (15% width, opacity 30%) so it does not distract from the reference list.',
},

{ num: 43, title: 'Questions and Discussion', tag: 'Close',
  content: [
    'Thank You',
    '',
    'Aditya Sanjay Jadhav  (242050010)',
    'Guide: Prof. Shrinivas Khedkar',
    '',
    'Dept. of Computer Engineering & IT',
    'VJTI Mumbai  |  M.Tech 2025-26',
  ],
  image: 'FILE: vjtilogo.jpg — Place the VJTI logo at the same position as Slide 1 (title slide), top-left corner. Mirror the title slide layout: dark navy blue background, "Thank You" and name text at centre. Keep it matching the opening slide for a clean, consistent close. No other images needed on this slide.',
},

];

// ─── Build the document ───────────────────────────────────────────────────────
const doc = new Document({
  styles: {
    default: { document: { run: { font: 'Calibri', size: 22 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 32, bold: true, color: '1F3864' },
        paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 } },
    ]
  },
  sections: [{
    properties: {
      page: { size: { width: 12240, height: 15840 }, margin: { top: 900, right: 900, bottom: 900, left: 1080 } }
    },
    children: [

      // Cover
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 1440, after: 240 },
        children: [new TextRun({ text: 'SmartGrid AI Audit Framework', bold: true, size: 48, color: '1F3864' })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
        children: [new TextRun({ text: 'PPTX Slide Content and Image Guide', bold: true, size: 28, color: '2E5A9C' })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
        children: [new TextRun({ text: 'All 43 slides — exact slide text + image placement notes', size: 22, italics: true, color: '555555' })] }),
      ...sp(2),
      new Paragraph({ alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: 'Aditya Sanjay Jadhav  (242050010)  |  Guide: Prof. Shrinivas Khedkar', bold: true, size: 22 })] }),
      new Paragraph({ alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: 'VJTI Mumbai  |  M.Tech 2025-26', size: 22 })] }),
      new Paragraph({ children: [new PageBreak()] }),

      // How to read
      new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: 'How to Read This Document', bold: true, size: 28, color: '1F3864' })] }),
      new Paragraph({ children: [new TextRun({ text: 'Each slide entry has three sections:', size: 22 })] }),
      ...sp(1),
      new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [1400, 7960], rows: [
        new TableRow({ children: [
          new TableCell({ borders, margins: pad, shading: { fill: '1F3864', type: ShadingType.CLEAR },
            children: [new Paragraph({ children: [new TextRun({ text: 'SLIDE HEADER', bold: true, size: 20, color: 'FFFFFF' })] })] }),
          new TableCell({ borders, margins: pad,
            children: [new Paragraph({ children: [new TextRun({ text: 'Slide number + title + category tag (e.g. NEW, Results, Architecture)', size: 20 })] })] }),
        ]}),
        new TableRow({ children: [
          new TableCell({ borders, margins: pad, shading: { fill: 'EBF2FA', type: ShadingType.CLEAR },
            children: [new Paragraph({ children: [new TextRun({ text: 'SLIDE CONTENT', bold: true, size: 20, color: '2E5A9C' })] })] }),
          new TableCell({ borders, margins: pad,
            children: [new Paragraph({ children: [new TextRun({ text: 'Exact text that appears on the PPTX slide — title + every bullet, sub-bullet, formula, and table row', size: 20 })] })] }),
        ]}),
        new TableRow({ children: [
          new TableCell({ borders, margins: pad, shading: { fill: 'F5F0FF', type: ShadingType.CLEAR },
            children: [new Paragraph({ children: [new TextRun({ text: 'IMG', bold: true, size: 20, color: '4B0082' })] })] }),
          new TableCell({ borders, margins: pad,
            children: [new Paragraph({ children: [new TextRun({ text: 'Detailed image suggestion — what to place on this slide, where, and what it should show', size: 20 })] })] }),
        ]}),
      ]}),
      ...sp(1),
      new Paragraph({ children: [new TextRun({ text: 'Slides marked NEW were added in v3 and were not in the original 32-slide deck.', size: 20, italics: true, color: '444444' })] }),
      new Paragraph({ children: [new PageBreak()] }),

      // All slides
      ...SLIDES.flatMap((s, i) => [
        slideHeader(s.num, s.title, s.tag),
        ...sp(1),
        new Paragraph({ children: [new TextRun({ text: 'SLIDE CONTENT', bold: true, size: 19, color: '2E5A9C' })] }),
        contentBox(s.content),
        ...sp(1),
        new Paragraph({ children: [new TextRun({ text: 'IMAGE PLACEMENT', bold: true, size: 19, color: '4B0082' })] }),
        imageBox(s.image),
        ...(i < SLIDES.length - 1 ? [new Paragraph({ children: [new PageBreak()] })] : []),
      ]),

      ...sp(2),
      new Paragraph({ alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: '--- End of PPTX Content and Image Guide ---', italics: true, size: 20, color: '888888' })] }),
    ]
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync(OUT, buf);
  console.log('Written:', OUT);
  console.log('Slides:', SLIDES.length);
});
